Pipewire 1.2.1
pop-os/pipewire pull request #77
Opened 2024-07-16 15:04 UTC by mmstick

2024-07-16 15:39 UTC, jacobgkau requested changes
I'm still experiencing the pang12 regression I described in #76. The speakers do not work on boot, and if I plug in headphones or a headset, I get sound from both the headphones/headset and the speakers at the same time. This still does not occur with the currently released version of PipeWire.

2024-07-17 01:51 UTC, ianhundere commented
@jacobgkau have you tried these respective configs to see if it alleviates your symptoms?
- [pipewire](https://github.com/robbert-vdh/dotfiles/tree/master/modules/pipewire/pipewire)
- [wireplumber/main.lua.d](https://github.com/robbert-vdh/dotfiles/tree/master/modules/pipewire/wireplumber/main.lua.d)

2024-07-17 01:55 UTC, mmstick commented
It's worth a try

2024-07-17 15:29 UTC, jacobgkau commented
@ianhundere Placing the three PipeWire config files in `/etc/pipewire/` and the WirePlumber config file in `/etc/wireplumber/main.lua.d/`, then rebooting, did not make the speakers work on boot on the pang12.

2024-07-17 15:31 UTC, mmstick commented
Perhaps I need to try updating wireplumber

2024-07-17 15:33 UTC, ianhundere commented
> Perhaps I need to try updating wireplumber

ah, that could be it. 🤔

2024-08-03 12:15 UTC, ianhundere commented
[1.2.2](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/1.2.2) just released, too

2024-10-09 13:39 UTC, ianhundere commented
@mmstick @jacobgkau any eta on this or is this an update we won't see until the next release of pop!_os ?

2024-10-09 15:02 UTC, jacobgkau commented
The ETA is whenever the pang12 regression is fixed. Once again, we can't ship an update that breaks one of our products' speakers.

2024-10-09 15:08 UTC, ianhundere commented
> As stated in [#77 (comment)](https://github.com/pop-os/pipewire/pull/77#issuecomment-2402593825), we're stuck on an older version because newer versions cause regressions on one of our products. If the regression goes away upstream or can be fixed in another component (e.g. a new quirk in the kernel or something), then we could proceed with an update.

ah, i completely missed that this was a regression in regards to one of y'all's supported products. no worries / thanks for explaining the issue further.

2025-01-28 15:37 UTC, ianhundere commented
@mmstick @jacobgkau could we try [1.3.81](https://gitlab.freedesktop.org/pipewire/pipewire/-/tags/1.3.81) ?

2025-01-28 16:20 UTC, mmstick commented
Pop 24.04 is currently on 1.2.7. 1.3.81 seems to be a release candidate for 1.4

2025-01-28 17:20 UTC, ianhundere commented
@mmstick thanks for the quick response / i suppose i should just bite the bullet and update to `Pop 24.04` 😅 

i suppose these are the best steps to follow if i do?

https://github.com/pop-os/cosmic-epoch?tab=readme-ov-file#installing-on-pop_os

2025-01-28 17:25 UTC, mmstick commented
That's for installing COSMIC on 22.04. If you want to upgrade to the 24.04 alpha, you can use `pop-upgrade release upgrade -f`.

2025-01-28 17:34 UTC, ianhundere commented
> That's for installing COSMIC on 22.04. If you want to upgrade to the 24.04 alpha, you can use `pop-upgrade release upgrade -f`.

ah, thank you / i had no idea it had released. 🙇

2025-01-28 20:58 UTC, jacobgkau commented
> i had no idea it had released.

It has not been released, it's still in alpha. The `-f` part of the command forces an upgrade to a non-released version.

2025-02-05 22:40 UTC, ianhundere commented
> > i had no idea it had released.
> 
> It has not been released, it's still in alpha. The `-f` part of the command forces an upgrade to a non-released version.

@mmstick / @jacobgkau do y'all have any suggestions for installing the latest vers of pipewire if i wanted to stay on `22.04` until `24.04` is ready? should i just uninstall pipewire/wireplumber and install from source or ?

2025-02-05 22:42 UTC, jacobgkau commented
Uninstalling could be a problem with apt dependencies. Probably you'd want to prepare a Debian repo (or grab one from Debian Salsa), similar to what Michael's been doing with these PRs, then build and install that locally. That way, apt will still know the package is installed, it'll just be your own version of it.

2026-08-25 20:37 UTC, closed without merging