Pipewire 1.0.7
pop-os/pipewire pull request #78
Opened 2024-07-17 19:47 UTC by mmstick

Required by https://github.com/pop-os/wireplumber/pull/19

2024-07-17 21:31 UTC, gabriele2000 commented
Isn't this a bit "old" than 1.2.1?
I've got pipewire video capture on latest OBS that doesn't work because it's too outdated, I hope this version will not be still problematic...

2024-07-17 21:45 UTC, mmstick commented
Wireplumber requires a newer version of 1.0.X to build for Jammy. Meanwhile, 1.2.X has regressions which might be solved by a newer version of Wireplumber.

2024-07-18 23:31 UTC, jacobgkau requested changes
This one's working fine on pang12.

This does seem to break GNOME Shell screen recording more than it already was. There have already been some known issues with that, such as the cursor not showing up properly in the recording, and the recording only working once per GNOME Shell session unless the gjs process is manually killed. However, with this update, the recordings basically stop working entirely; they only seem to capture one or two frames, and produce a video that only lasts a split second (when played via MPV or VLC).

I've confirmed this regression occurs on multiple machines, on Intel, AMD, and NVIDIA graphics. The screen recorder worked on all three machines prior to the update, and no longer works after the update. I did notice that the filesize for the broken recordings are still comparable to the working ones. Based on the behavior in different video players, it seems likely this is some kind of reported framerate or other encoding error besides simply not saving the data.

The rest of regression testing passed. I could see a case for giving up on the built-in screen recording since it already worked poorly, but on the other hand, there has been a workaround available to at least make it work, and we know from issues such as https://github.com/pop-os/gnome-shell/issues/134 that people are still using the functionality. For that reason, I think that should count as a blocker from a QA standpoint.

<details>
<summary>Full checklist:</summary>

- [X] Built-in speakers and microphone still work, volume adjustment still plays sound.
- [X] GNOME Sound Recorder still records and plays back.
- [X] Audacity records and plays back.
    - [X] JACK mode
    - [X] ALSA mode
- [X] DaVinci Resolve audio still works as expected (without lag) & shows up in pavucontrol.
    - Volume adjustment sounds stop working when Resolve is open, not a regression.
- [X] Ardour works in JACK mode, Bitwig works in native PipeWire mode.
- [X] Output via GPU (e.g. HDMI and DisplayPort audio) works.
    - [X] Intel GPU system
    - [X] NVIDIA GPU system
    - [X] AMD GPU system
- [X] Headphone/microphone and combo headset both work.
- [ ] Built-in GNOME Shell screen recording still works.
    - Option to show cursor is broken, stuck in top-left in recording (not a regression).
    - Only starts recording once per GNOME Shell restart (not a regression).
    - Only records for a brief instant (this is a regression).
- [X] Still able to share screen, webcam, and microphone via Jitsi in Firefox.
- [X] Bluetooth microphone input works with no stuttering.
</details>

2024-08-03 12:16 UTC, ianhundere commented
any progress on this?

2026-08-25 20:37 UTC, closed without merging